# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cameraParms.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1113, 854)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(130, 60, 281, 338))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.meterModes = QtWidgets.QComboBox(self.formLayoutWidget)
        self.meterModes.setObjectName("meterModes")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.meterModes)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.exposureModes = QtWidgets.QComboBox(self.formLayoutWidget)
        self.exposureModes.setObjectName("exposureModes")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.exposureModes)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.flashModes = QtWidgets.QComboBox(self.formLayoutWidget)
        self.flashModes.setObjectName("flashModes")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.flashModes)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.awbModes = QtWidgets.QComboBox(self.formLayoutWidget)
        self.awbModes.setObjectName("awbModes")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.awbModes)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.imageEffects = QtWidgets.QComboBox(self.formLayoutWidget)
        self.imageEffects.setObjectName("imageEffects")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.imageEffects)
        self.drcStrengths = QtWidgets.QComboBox(self.formLayoutWidget)
        self.drcStrengths.setObjectName("drcStrengths")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.drcStrengths)
        self.rawFormats = QtWidgets.QComboBox(self.formLayoutWidget)
        self.rawFormats.setObjectName("rawFormats")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.rawFormats)
        self.stereoModes = QtWidgets.QComboBox(self.formLayoutWidget)
        self.stereoModes.setObjectName("stereoModes")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.stereoModes)
        self.clockModes = QtWidgets.QComboBox(self.formLayoutWidget)
        self.clockModes.setObjectName("clockModes")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.clockModes)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(510, 380, 261, 91))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.dial = QtWidgets.QDial(self.formLayoutWidget_2)
        self.dial.setMinimum(-100)
        self.dial.setMaximum(100)
        self.dial.setObjectName("dial")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.dial)
        self.spinBox = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.spinBox.setMinimum(-100)
        self.spinBox.setMaximum(100)
        self.spinBox.setObjectName("spinBox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox)
        self.dial_2 = QtWidgets.QDial(self.centralwidget)
        self.dial_2.setGeometry(QtCore.QRect(200, 630, 50, 64))
        self.dial_2.setObjectName("dial_2")
        self.spinBox_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_2.setGeometry(QtCore.QRect(280, 650, 50, 32))
        self.spinBox_2.setObjectName("spinBox_2")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(480, 80, 241, 171))
        self.label_10.setObjectName("label_10")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1113, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.dial.sliderMoved['int'].connect(self.spinBox.setValue)
        self.spinBox.valueChanged['int'].connect(self.dial.setValue)
        self.dial_2.sliderMoved['int'].connect(MainWindow.doWork)
        self.spinBox_2.valueChanged['int'].connect(MainWindow.doWork)
        self.dial_2.sliderMoved['int'].connect(self.spinBox_2.setValue)
        self.spinBox_2.valueChanged['int'].connect(self.dial_2.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Meter Modes"))
        self.label_2.setText(_translate("MainWindow", "Exposure Modes"))
        self.label_3.setText(_translate("MainWindow", "Flash Modes"))
        self.label_4.setText(_translate("MainWindow", "AWB Modes"))
        self.label_5.setText(_translate("MainWindow", "Image Effects"))
        self.label_6.setText(_translate("MainWindow", "DRC Strengths"))
        self.label_7.setText(_translate("MainWindow", "Raw Formats"))
        self.label_8.setText(_translate("MainWindow", "Stereo Modes"))
        self.label_9.setText(_translate("MainWindow", "Clock Modes"))
        self.dial_2.setProperty("parmType", _translate("MainWindow", "cameraParm1"))
        self.spinBox_2.setProperty("parmType", _translate("MainWindow", "cameraParm1"))
        self.label_10.setText(_translate("MainWindow", "TextLabel"))

