# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cameraApp.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1500, 850)
        MainWindow.setIconSize(QtCore.QSize(128, 96))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.captureTab = QtWidgets.QTabWidget(self.centralwidget)
        self.captureTab.setGeometry(QtCore.QRect(670, 680, 801, 111))
        self.captureTab.setObjectName("captureTab")
        self.still = QtWidgets.QWidget()
        self.still.setObjectName("still")
        self.pushButton_4 = QtWidgets.QPushButton(self.still)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 20, 99, 30))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.still)
        self.pushButton_5.setGeometry(QtCore.QRect(140, 20, 99, 30))
        self.pushButton_5.setObjectName("pushButton_5")
        self.isCounter = QtWidgets.QRadioButton(self.still)
        self.isCounter.setGeometry(QtCore.QRect(620, 20, 119, 27))
        self.isCounter.setChecked(True)
        self.isCounter.setObjectName("isCounter")
        self.isDatestamp = QtWidgets.QRadioButton(self.still)
        self.isDatestamp.setGeometry(QtCore.QRect(500, 20, 119, 27))
        self.isDatestamp.setObjectName("isDatestamp")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.still)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(270, 20, 160, 34))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_15.setObjectName("label_15")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.fileRoot = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.fileRoot.setObjectName("fileRoot")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fileRoot)
        self.captureTab.addTab(self.still, "")
        self.video = QtWidgets.QWidget()
        self.video.setObjectName("video")
        self.vidPosSlider = QtWidgets.QSlider(self.video)
        self.vidPosSlider.setGeometry(QtCore.QRect(220, 30, 571, 26))
        self.vidPosSlider.setMaximum(1000)
        self.vidPosSlider.setOrientation(QtCore.Qt.Horizontal)
        self.vidPosSlider.setObjectName("vidPosSlider")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.video)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 196, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.startRecordVid = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.startRecordVid.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/media-record.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startRecordVid.setIcon(icon)
        self.startRecordVid.setObjectName("startRecordVid")
        self.horizontalLayout_2.addWidget(self.startRecordVid)
        self.playVid = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.playVid.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/media-playback-start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playVid.setIcon(icon1)
        self.playVid.setObjectName("playVid")
        self.horizontalLayout_2.addWidget(self.playVid)
        self.stopVid = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.stopVid.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/media-playback-stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopVid.setIcon(icon2)
        self.stopVid.setObjectName("stopVid")
        self.horizontalLayout_2.addWidget(self.stopVid)
        self.pauseVid = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pauseVid.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/media-playback-pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pauseVid.setIcon(icon3)
        self.pauseVid.setObjectName("pauseVid")
        self.horizontalLayout_2.addWidget(self.pauseVid)
        self.captureTab.addTab(self.video, "")
        self.previewVisible = QtWidgets.QCheckBox(self.centralwidget)
        self.previewVisible.setGeometry(QtCore.QRect(670, 650, 101, 27))
        self.previewVisible.setObjectName("previewVisible")
        self.resizePreview = QtWidgets.QSlider(self.centralwidget)
        self.resizePreview.setGeometry(QtCore.QRect(790, 650, 591, 26))
        self.resizePreview.setOrientation(QtCore.Qt.Horizontal)
        self.resizePreview.setObjectName("resizePreview")
        self.imgContainer = QtWidgets.QLabel(self.centralwidget)
        self.imgContainer.setGeometry(QtCore.QRect(670, 40, 800, 600))
        self.imgContainer.setFrameShape(QtWidgets.QFrame.Box)
        self.imgContainer.setText("")
        self.imgContainer.setObjectName("imgContainer")
        self.thumbnails = QtWidgets.QListWidget(self.centralwidget)
        self.thumbnails.setGeometry(QtCore.QRect(500, 40, 140, 601))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.thumbnails.setFont(font)
        self.thumbnails.setIconSize(QtCore.QSize(128, 96))
        self.thumbnails.setViewMode(QtWidgets.QListView.IconMode)
        self.thumbnails.setWordWrap(True)
        self.thumbnails.setObjectName("thumbnails")
        self.mainTab = QtWidgets.QTabWidget(self.centralwidget)
        self.mainTab.setGeometry(QtCore.QRect(20, 10, 441, 781))
        self.mainTab.setObjectName("mainTab")
        self.resolutions = QtWidgets.QWidget()
        self.resolutions.setObjectName("resolutions")
        self.formLayoutWidget = QtWidgets.QWidget(self.resolutions)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 40, 321, 191))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.lstartX = QtWidgets.QLabel(self.formLayoutWidget)
        self.lstartX.setObjectName("lstartX")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lstartX)
        self.lstartY = QtWidgets.QLabel(self.formLayoutWidget)
        self.lstartY.setObjectName("lstartY")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lstartY)
        self.wStartWidth = QtWidgets.QLabel(self.formLayoutWidget)
        self.wStartWidth.setObjectName("wStartWidth")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.wStartWidth)
        self.lStartHeight = QtWidgets.QLabel(self.formLayoutWidget)
        self.lStartHeight.setObjectName("lStartHeight")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lStartHeight)
        self.fixStartZoom = QtWidgets.QPushButton(self.formLayoutWidget)
        self.fixStartZoom.setObjectName("fixStartZoom")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.fixStartZoom)
        self.zStartX = CompositeSlider(self.formLayoutWidget)
        self.zStartX.setObjectName("zStartX")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.zStartX)
        self.zStartY = CompositeSlider(self.formLayoutWidget)
        self.zStartY.setObjectName("zStartY")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.zStartY)
        self.zStartWidth = CompositeSlider(self.formLayoutWidget)
        self.zStartWidth.setObjectName("zStartWidth")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.zStartWidth)
        self.zStartHeight = CompositeSlider(self.formLayoutWidget)
        self.zStartHeight.setObjectName("zStartHeight")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.zStartHeight)
        self.label_13 = QtWidgets.QLabel(self.resolutions)
        self.label_13.setGeometry(QtCore.QRect(20, 10, 91, 22))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.resolutions)
        self.label_14.setGeometry(QtCore.QRect(20, 230, 81, 22))
        self.label_14.setObjectName("label_14")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.resolutions)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(20, 260, 321, 191))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.lEndX = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lEndX.setObjectName("lEndX")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lEndX)
        self.lEndY = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lEndY.setObjectName("lEndY")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lEndY)
        self.lEndWidth = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lEndWidth.setObjectName("lEndWidth")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lEndWidth)
        self.lEndHeight = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lEndHeight.setObjectName("lEndHeight")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lEndHeight)
        self.fixEndZoom = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.fixEndZoom.setObjectName("fixEndZoom")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.fixEndZoom)
        self.zEndX = CompositeSlider(self.formLayoutWidget_2)
        self.zEndX.setObjectName("zEndX")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.zEndX)
        self.zEndY = CompositeSlider(self.formLayoutWidget_2)
        self.zEndY.setObjectName("zEndY")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.zEndY)
        self.zEndWidth = CompositeSlider(self.formLayoutWidget_2)
        self.zEndWidth.setObjectName("zEndWidth")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.zEndWidth)
        self.zEndHeight = CompositeSlider(self.formLayoutWidget_2)
        self.zEndHeight.setObjectName("zEndHeight")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.zEndHeight)
        self.label_16 = QtWidgets.QLabel(self.resolutions)
        self.label_16.setGeometry(QtCore.QRect(20, 460, 81, 22))
        self.label_16.setObjectName("label_16")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.resolutions)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(20, 490, 321, 191))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_5 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.lEndX_2 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.lEndX_2.setObjectName("lEndX_2")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lEndX_2)
        self.lEndY_2 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.lEndY_2.setObjectName("lEndY_2")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lEndY_2)
        self.lEndWidth_2 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.lEndWidth_2.setObjectName("lEndWidth_2")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lEndWidth_2)
        self.lEndHeight_2 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.lEndHeight_2.setObjectName("lEndHeight_2")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lEndHeight_2)
        self.fixZoom = QtWidgets.QPushButton(self.formLayoutWidget_4)
        self.fixZoom.setObjectName("fixZoom")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.fixZoom)
        self.zoomX = CompositeSlider(self.formLayoutWidget_4)
        self.zoomX.setObjectName("zoomX")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.zoomX)
        self.zoomY = CompositeSlider(self.formLayoutWidget_4)
        self.zoomY.setObjectName("zoomY")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.zoomY)
        self.zoomWidth = CompositeSlider(self.formLayoutWidget_4)
        self.zoomWidth.setObjectName("zoomWidth")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.zoomWidth)
        self.zoomHeight = CompositeSlider(self.formLayoutWidget_4)
        self.zoomHeight.setObjectName("zoomHeight")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.zoomHeight)
        self.mainTab.addTab(self.resolutions, "")
        self.adjustments = QtWidgets.QWidget()
        self.adjustments.setObjectName("adjustments")
        self.formLayoutWidget_5 = QtWidgets.QWidget(self.adjustments)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(40, 40, 371, 271))
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.brightness = CompositeSlider(self.formLayoutWidget_5)
        self.brightness.setObjectName("brightness")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.brightness)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.saturation = CompositeSlider(self.formLayoutWidget_5)
        self.saturation.setObjectName("saturation")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.saturation)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.contrast = CompositeSlider(self.formLayoutWidget_5)
        self.contrast.setObjectName("contrast")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.contrast)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.sharpness = CompositeSlider(self.formLayoutWidget_5)
        self.sharpness.setObjectName("sharpness")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sharpness)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.exposure_compensation = CompositeSlider(self.formLayoutWidget_5)
        self.exposure_compensation.setObjectName("exposure_compensation")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.exposure_compensation)
        self.formLayoutWidget_6 = QtWidgets.QWidget(self.adjustments)
        self.formLayoutWidget_6.setGeometry(QtCore.QRect(40, 350, 281, 338))
        self.formLayoutWidget_6.setObjectName("formLayoutWidget_6")
        self.formLayout_6 = QtWidgets.QFormLayout(self.formLayoutWidget_6)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_5.setObjectName("label_5")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.meter_mode = QtWidgets.QComboBox(self.formLayoutWidget_6)
        self.meter_mode.setEnabled(True)
        self.meter_mode.setObjectName("meter_mode")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.meter_mode)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_6.setObjectName("label_6")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.exposure_mode = QtWidgets.QComboBox(self.formLayoutWidget_6)
        self.exposure_mode.setEnabled(True)
        self.exposure_mode.setObjectName("exposure_mode")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.exposure_mode)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_7.setObjectName("label_7")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.flash_mode = QtWidgets.QComboBox(self.formLayoutWidget_6)
        self.flash_mode.setEnabled(True)
        self.flash_mode.setObjectName("flash_mode")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.flash_mode)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_8.setObjectName("label_8")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.awb_mode = QtWidgets.QComboBox(self.formLayoutWidget_6)
        self.awb_mode.setEnabled(True)
        self.awb_mode.setObjectName("awb_mode")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.awb_mode)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_9.setObjectName("label_9")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.image_effect = QtWidgets.QComboBox(self.formLayoutWidget_6)
        self.image_effect.setEnabled(True)
        self.image_effect.setObjectName("image_effect")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.image_effect)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_10.setObjectName("label_10")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.drc_strength = QtWidgets.QComboBox(self.formLayoutWidget_6)
        self.drc_strength.setEnabled(True)
        self.drc_strength.setObjectName("drc_strength")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.drc_strength)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_11.setObjectName("label_11")
        self.formLayout_6.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.raw_format = QtWidgets.QComboBox(self.formLayoutWidget_6)
        self.raw_format.setEnabled(True)
        self.raw_format.setObjectName("raw_format")
        self.formLayout_6.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.raw_format)
        self.label_17 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_17.setObjectName("label_17")
        self.formLayout_6.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.clock_mode = QtWidgets.QComboBox(self.formLayoutWidget_6)
        self.clock_mode.setEnabled(True)
        self.clock_mode.setObjectName("clock_mode")
        self.formLayout_6.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.clock_mode)
        self.mainTab.addTab(self.adjustments, "")
        self.advanced = QtWidgets.QWidget()
        self.advanced.setObjectName("advanced")
        self.mainTab.addTab(self.advanced, "")
        self.obscure = QtWidgets.QWidget()
        self.obscure.setObjectName("obscure")
        self.mainTab.addTab(self.obscure, "")
        self.thumbnails.raise_()
        self.captureTab.raise_()
        self.previewVisible.raise_()
        self.resizePreview.raise_()
        self.imgContainer.raise_()
        self.mainTab.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1500, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.captureTab.setCurrentIndex(0)
        self.mainTab.setCurrentIndex(1)
        self.fixStartZoom.clicked.connect(MainWindow.setZoomStart)
        self.fixEndZoom.clicked.connect(MainWindow.setZoomEnd)
        self.pushButton_4.clicked.connect(MainWindow.snapAndSave)
        self.pushButton_5.clicked.connect(MainWindow.snapAndHold)
        self.fileRoot.textChanged['QString'].connect(MainWindow.setFileRoot)
        self.isDatestamp.clicked.connect(MainWindow.isDateStamp)
        self.isCounter.clicked.connect(MainWindow.isCounter)
        self.previewVisible.clicked['bool'].connect(MainWindow.showPreview)
        self.resizePreview.valueChanged['int'].connect(MainWindow.setPreviewSize)
        self.captureTab.currentChanged['int'].connect(MainWindow.setupVid)
        self.startRecordVid.clicked['bool'].connect(MainWindow.doRecordVid)
        self.playVid.clicked['bool'].connect(MainWindow.doPlayVid)
        self.stopVid.clicked.connect(MainWindow.doStopVid)
        self.pauseVid.clicked['bool'].connect(MainWindow.doPauseVid)
        self.vidPosSlider.sliderMoved['int'].connect(MainWindow.setPosition)
        self.fixZoom.clicked.connect(MainWindow.setZoom)
        self.meter_mode.currentIndexChanged['QString'].connect(MainWindow.setCamValFromCombo)
        self.exposure_mode.currentIndexChanged['QString'].connect(MainWindow.setCamValFromCombo)
        self.flash_mode.currentIndexChanged['QString'].connect(MainWindow.setCamValFromCombo)
        self.awb_mode.currentIndexChanged['QString'].connect(MainWindow.setCamValFromCombo)
        self.image_effect.currentIndexChanged['QString'].connect(MainWindow.setCamValFromCombo)
        self.drc_strength.currentIndexChanged['QString'].connect(MainWindow.setCamValFromCombo)
        self.raw_format.currentIndexChanged['QString'].connect(MainWindow.setCamValFromCombo)
        self.clock_mode.currentIndexChanged['QString'].connect(MainWindow.setCamValFromCombo)
        self.thumbnails.itemDoubleClicked['QListWidgetItem*'].connect(MainWindow.fetchItemToPlayer)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_4.setText(_translate("MainWindow", "Snap/Save"))
        self.pushButton_5.setText(_translate("MainWindow", "Snap/Hold"))
        self.isCounter.setText(_translate("MainWindow", "Counter "))
        self.isDatestamp.setText(_translate("MainWindow", "Datestamp"))
        self.label_15.setText(_translate("MainWindow", "File root"))
        self.fileRoot.setText(_translate("MainWindow", "img_"))
        self.captureTab.setTabText(self.captureTab.indexOf(self.still), _translate("MainWindow", "Still"))
        self.captureTab.setTabText(self.captureTab.indexOf(self.video), _translate("MainWindow", "Video"))
        self.previewVisible.setText(_translate("MainWindow", "Preview"))
        self.lstartX.setText(_translate("MainWindow", "X"))
        self.lstartY.setText(_translate("MainWindow", "Y"))
        self.wStartWidth.setText(_translate("MainWindow", "Width"))
        self.lStartHeight.setText(_translate("MainWindow", "Height"))
        self.fixStartZoom.setText(_translate("MainWindow", "Apply"))
        self.label_13.setText(_translate("MainWindow", "Zoom Start"))
        self.label_14.setText(_translate("MainWindow", "Zoom End"))
        self.lEndX.setText(_translate("MainWindow", "X"))
        self.lEndY.setText(_translate("MainWindow", "Y"))
        self.lEndWidth.setText(_translate("MainWindow", "Width"))
        self.lEndHeight.setText(_translate("MainWindow", "Height"))
        self.fixEndZoom.setText(_translate("MainWindow", "Apply"))
        self.label_16.setText(_translate("MainWindow", "Zoom"))
        self.lEndX_2.setText(_translate("MainWindow", "X"))
        self.lEndY_2.setText(_translate("MainWindow", "Y"))
        self.lEndWidth_2.setText(_translate("MainWindow", "Width"))
        self.lEndHeight_2.setText(_translate("MainWindow", "Height"))
        self.fixZoom.setText(_translate("MainWindow", "Apply"))
        self.mainTab.setTabText(self.mainTab.indexOf(self.resolutions), _translate("MainWindow", "Resolutions"))
        self.label.setText(_translate("MainWindow", "Brightness"))
        self.label_2.setText(_translate("MainWindow", "Saturation"))
        self.label_3.setText(_translate("MainWindow", "Contrast"))
        self.label_4.setText(_translate("MainWindow", "Sharpness"))
        self.label_12.setText(_translate("MainWindow", "Exposure Comp."))
        self.label_5.setText(_translate("MainWindow", "Meter Modes"))
        self.label_6.setText(_translate("MainWindow", "Exposure Modes"))
        self.label_7.setText(_translate("MainWindow", "Flash Modes"))
        self.label_8.setText(_translate("MainWindow", "AWB Modes"))
        self.label_9.setText(_translate("MainWindow", "Image Effects"))
        self.label_10.setText(_translate("MainWindow", "DRC Strengths"))
        self.label_11.setText(_translate("MainWindow", "Raw Formats"))
        self.label_17.setText(_translate("MainWindow", "Clock Modes"))
        self.mainTab.setTabText(self.mainTab.indexOf(self.adjustments), _translate("MainWindow", "Adjustments"))
        self.mainTab.setTabText(self.mainTab.indexOf(self.advanced), _translate("MainWindow", "Advanced"))
        self.mainTab.setTabText(self.mainTab.indexOf(self.obscure), _translate("MainWindow", "Obscure"))

from mysliders import CompositeSlider
import resource_rc
