# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'leasCameraApp.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1091, 887)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 741, 811))
        self.tabWidget.setObjectName("tabWidget")
        self.basic = QtWidgets.QWidget()
        self.basic.setObjectName("basic")
        self.portSelection = QtWidgets.QFrame(self.basic)
        self.portSelection.setGeometry(QtCore.QRect(20, 40, 491, 81))
        self.portSelection.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.portSelection.setFrameShadow(QtWidgets.QFrame.Raised)
        self.portSelection.setObjectName("portSelection")
        self.portStill = QtWidgets.QRadioButton(self.portSelection)
        self.portStill.setGeometry(QtCore.QRect(10, 10, 141, 27))
        self.portStill.setChecked(True)
        self.portStill.setObjectName("portStill")
        self.portVideo = QtWidgets.QRadioButton(self.portSelection)
        self.portVideo.setGeometry(QtCore.QRect(190, 10, 192, 27))
        self.portVideo.setObjectName("portVideo")
        self.checkBox_2 = QtWidgets.QCheckBox(self.portSelection)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 50, 135, 27))
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.portSelection)
        self.checkBox_3.setGeometry(QtCore.QRect(140, 50, 161, 27))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox = QtWidgets.QCheckBox(self.portSelection)
        self.checkBox.setGeometry(QtCore.QRect(310, 50, 141, 27))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.portSelectionLabel = QtWidgets.QLabel(self.basic)
        self.portSelectionLabel.setGeometry(QtCore.QRect(20, 10, 221, 22))
        self.portSelectionLabel.setObjectName("portSelectionLabel")
        self.resolutionSelection = QtWidgets.QFrame(self.basic)
        self.resolutionSelection.setGeometry(QtCore.QRect(20, 160, 491, 201))
        self.resolutionSelection.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.resolutionSelection.setFrameShadow(QtWidgets.QFrame.Raised)
        self.resolutionSelection.setObjectName("resolutionSelection")
        self.fixedRes = QtWidgets.QRadioButton(self.resolutionSelection)
        self.fixedRes.setGeometry(QtCore.QRect(10, 10, 119, 27))
        self.fixedRes.setObjectName("fixedRes")
        self.comboBox = QtWidgets.QComboBox(self.resolutionSelection)
        self.comboBox.setGeometry(QtCore.QRect(120, 10, 241, 21))
        self.comboBox.setObjectName("comboBox")
        self.customRes = QtWidgets.QRadioButton(self.resolutionSelection)
        self.customRes.setGeometry(QtCore.QRect(10, 40, 141, 27))
        self.customRes.setObjectName("customRes")
        self.widthComboLabel = QtWidgets.QLabel(self.resolutionSelection)
        self.widthComboLabel.setGeometry(QtCore.QRect(160, 40, 68, 22))
        self.widthComboLabel.setObjectName("widthComboLabel")
        self.comboBox_2 = QtWidgets.QComboBox(self.resolutionSelection)
        self.comboBox_2.setGeometry(QtCore.QRect(210, 40, 83, 21))
        self.comboBox_2.setObjectName("comboBox_2")
        self.heightComboLabel = QtWidgets.QLabel(self.resolutionSelection)
        self.heightComboLabel.setGeometry(QtCore.QRect(310, 40, 51, 22))
        self.heightComboLabel.setObjectName("heightComboLabel")
        self.comboBox_3 = QtWidgets.QComboBox(self.resolutionSelection)
        self.comboBox_3.setGeometry(QtCore.QRect(360, 40, 83, 21))
        self.comboBox_3.setObjectName("comboBox_3")
        self.actualWidthLabel = QtWidgets.QLabel(self.resolutionSelection)
        self.actualWidthLabel.setGeometry(QtCore.QRect(140, 70, 68, 22))
        self.actualWidthLabel.setObjectName("actualWidthLabel")
        self.actualheight = QtWidgets.QLabel(self.resolutionSelection)
        self.actualheight.setGeometry(QtCore.QRect(210, 70, 68, 22))
        self.actualheight.setStyleSheet("color: darkblue\n"
"")
        self.actualheight.setObjectName("actualheight")
        self.actualHeightLabel = QtWidgets.QLabel(self.resolutionSelection)
        self.actualHeightLabel.setGeometry(QtCore.QRect(300, 70, 68, 22))
        self.actualHeightLabel.setObjectName("actualHeightLabel")
        self.actualwidth = QtWidgets.QLabel(self.resolutionSelection)
        self.actualwidth.setGeometry(QtCore.QRect(380, 70, 68, 22))
        self.actualwidth.setStyleSheet("color:darkblue\n"
"")
        self.actualwidth.setObjectName("actualwidth")
        self.line = QtWidgets.QFrame(self.resolutionSelection)
        self.line.setGeometry(QtCore.QRect(10, 90, 451, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.zoomSelectionLabel = QtWidgets.QLabel(self.resolutionSelection)
        self.zoomSelectionLabel.setGeometry(QtCore.QRect(10, 100, 381, 22))
        self.zoomSelectionLabel.setObjectName("zoomSelectionLabel")
        self.frame = QtWidgets.QFrame(self.resolutionSelection)
        self.frame.setGeometry(QtCore.QRect(10, 130, 471, 61))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.xSlider = QtWidgets.QSlider(self.frame)
        self.xSlider.setGeometry(QtCore.QRect(50, 0, 160, 26))
        self.xSlider.setMaximum(255)
        self.xSlider.setSingleStep(1)
        self.xSlider.setOrientation(QtCore.Qt.Horizontal)
        self.xSlider.setTickInterval(2)
        self.xSlider.setObjectName("xSlider")
        self.ySlider = QtWidgets.QSlider(self.frame)
        self.ySlider.setGeometry(QtCore.QRect(250, 0, 160, 26))
        self.ySlider.setMaximum(255)
        self.ySlider.setOrientation(QtCore.Qt.Horizontal)
        self.ySlider.setObjectName("ySlider")
        self.widthSlider = QtWidgets.QSlider(self.frame)
        self.widthSlider.setGeometry(QtCore.QRect(50, 30, 160, 26))
        self.widthSlider.setMaximum(255)
        self.widthSlider.setOrientation(QtCore.Qt.Horizontal)
        self.widthSlider.setObjectName("widthSlider")
        self.heightSlider = QtWidgets.QSlider(self.frame)
        self.heightSlider.setGeometry(QtCore.QRect(250, 30, 160, 26))
        self.heightSlider.setMaximum(255)
        self.heightSlider.setOrientation(QtCore.Qt.Horizontal)
        self.heightSlider.setObjectName("heightSlider")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(410, 10, 51, 41))
        self.pushButton.setObjectName("pushButton")
        self.resizeSelection = QtWidgets.QFrame(self.basic)
        self.resizeSelection.setGeometry(QtCore.QRect(20, 390, 491, 51))
        self.resizeSelection.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.resizeSelection.setFrameShadow(QtWidgets.QFrame.Raised)
        self.resizeSelection.setObjectName("resizeSelection")
        self.radioButton_5 = QtWidgets.QRadioButton(self.resizeSelection)
        self.radioButton_5.setGeometry(QtCore.QRect(10, 0, 131, 27))
        self.radioButton_5.setChecked(True)
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.resizeSelection)
        self.radioButton_6.setGeometry(QtCore.QRect(160, 0, 119, 27))
        self.radioButton_6.setObjectName("radioButton_6")
        self.resizeWidth = QtWidgets.QComboBox(self.resizeSelection)
        self.resizeWidth.setGeometry(QtCore.QRect(270, 10, 51, 21))
        self.resizeWidth.setObjectName("resizeWidth")
        self.resizeHeight = QtWidgets.QComboBox(self.resizeSelection)
        self.resizeHeight.setGeometry(QtCore.QRect(360, 12, 51, 20))
        self.resizeHeight.setObjectName("resizeHeight")
        self.adjustmentSelection = QtWidgets.QFrame(self.basic)
        self.adjustmentSelection.setGeometry(QtCore.QRect(30, 490, 481, 80))
        self.adjustmentSelection.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.adjustmentSelection.setFrameShadow(QtWidgets.QFrame.Raised)
        self.adjustmentSelection.setObjectName("adjustmentSelection")
        self.brightnessLabel = QtWidgets.QLabel(self.adjustmentSelection)
        self.brightnessLabel.setGeometry(QtCore.QRect(20, 10, 81, 22))
        self.brightnessLabel.setObjectName("brightnessLabel")
        self.contrastLabel = QtWidgets.QLabel(self.adjustmentSelection)
        self.contrastLabel.setGeometry(QtCore.QRect(270, 0, 68, 22))
        self.contrastLabel.setObjectName("contrastLabel")
        self.saturationLabel = QtWidgets.QLabel(self.adjustmentSelection)
        self.saturationLabel.setGeometry(QtCore.QRect(20, 40, 81, 22))
        self.saturationLabel.setObjectName("saturationLabel")
        self.sharpnessLabel = QtWidgets.QLabel(self.adjustmentSelection)
        self.sharpnessLabel.setGeometry(QtCore.QRect(270, 40, 81, 22))
        self.sharpnessLabel.setObjectName("sharpnessLabel")
        self.brightnessSlider = QtWidgets.QSlider(self.adjustmentSelection)
        self.brightnessSlider.setGeometry(QtCore.QRect(110, 10, 160, 26))
        self.brightnessSlider.setOrientation(QtCore.Qt.Horizontal)
        self.brightnessSlider.setObjectName("brightnessSlider")
        self.contrastSlider = QtWidgets.QSlider(self.adjustmentSelection)
        self.contrastSlider.setGeometry(QtCore.QRect(330, 0, 160, 26))
        self.contrastSlider.setOrientation(QtCore.Qt.Horizontal)
        self.contrastSlider.setObjectName("contrastSlider")
        self.horizontalSlider = QtWidgets.QSlider(self.adjustmentSelection)
        self.horizontalSlider.setGeometry(QtCore.QRect(110, 40, 160, 26))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.sharpnessSlider = QtWidgets.QSlider(self.adjustmentSelection)
        self.sharpnessSlider.setGeometry(QtCore.QRect(310, 30, 160, 26))
        self.sharpnessSlider.setOrientation(QtCore.Qt.Horizontal)
        self.sharpnessSlider.setObjectName("sharpnessSlider")
        self.effectSelection = QtWidgets.QFrame(self.basic)
        self.effectSelection.setGeometry(QtCore.QRect(30, 600, 481, 41))
        self.effectSelection.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.effectSelection.setFrameShadow(QtWidgets.QFrame.Raised)
        self.effectSelection.setObjectName("effectSelection")
        self.noEffect = QtWidgets.QRadioButton(self.effectSelection)
        self.noEffect.setGeometry(QtCore.QRect(10, 0, 119, 27))
        self.noEffect.setObjectName("noEffect")
        self.effectSelectCombo = QtWidgets.QComboBox(self.effectSelection)
        self.effectSelectCombo.setGeometry(QtCore.QRect(270, 10, 131, 21))
        self.effectSelectCombo.setObjectName("effectSelectCombo")
        self.selectEffect = QtWidgets.QRadioButton(self.effectSelection)
        self.selectEffect.setGeometry(QtCore.QRect(90, 0, 119, 27))
        self.selectEffect.setObjectName("selectEffect")
        self.flashSelection = QtWidgets.QFrame(self.basic)
        self.flashSelection.setGeometry(QtCore.QRect(30, 680, 481, 80))
        self.flashSelection.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.flashSelection.setFrameShadow(QtWidgets.QFrame.Raised)
        self.flashSelection.setObjectName("flashSelection")
        self.resSelectionLabel = QtWidgets.QLabel(self.basic)
        self.resSelectionLabel.setGeometry(QtCore.QRect(20, 130, 261, 22))
        self.resSelectionLabel.setObjectName("resSelectionLabel")
        self.resizeSelectionLabel = QtWidgets.QLabel(self.basic)
        self.resizeSelectionLabel.setGeometry(QtCore.QRect(20, 370, 311, 22))
        self.resizeSelectionLabel.setObjectName("resizeSelectionLabel")
        self.adjustmentSelectionLabel = QtWidgets.QLabel(self.basic)
        self.adjustmentSelectionLabel.setGeometry(QtCore.QRect(10, 470, 161, 22))
        self.adjustmentSelectionLabel.setObjectName("adjustmentSelectionLabel")
        self.effectSelectionLabel = QtWidgets.QLabel(self.basic)
        self.effectSelectionLabel.setGeometry(QtCore.QRect(30, 570, 231, 22))
        self.effectSelectionLabel.setObjectName("effectSelectionLabel")
        self.flashSelectionLabel = QtWidgets.QLabel(self.basic)
        self.flashSelectionLabel.setGeometry(QtCore.QRect(30, 650, 201, 22))
        self.flashSelectionLabel.setObjectName("flashSelectionLabel")
        self.tabWidget.addTab(self.basic, "")
        self.exposure = QtWidgets.QWidget()
        self.exposure.setObjectName("exposure")
        self.tabWidget.addTab(self.exposure, "")
        self.advanced = QtWidgets.QWidget()
        self.advanced.setObjectName("advanced")
        self.tabWidget.addTab(self.advanced, "")
        self.dial = QtWidgets.QDial(self.centralwidget)
        self.dial.setGeometry(QtCore.QRect(800, 720, 50, 64))
        self.dial.setMaximum(255)
        self.dial.setObjectName("dial")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.checkBox.clicked['bool'].connect(MainWindow.setImageDenoise)
        self.portVideo.clicked['bool'].connect(MainWindow.setPortVideo)
        self.portStill.clicked['bool'].connect(MainWindow.setPortStill)
        self.checkBox_2.clicked['bool'].connect(MainWindow.setVideoDenoise)
        self.checkBox_3.clicked['bool'].connect(MainWindow.setVideoStabilization)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.basic.setProperty("tabText", _translate("MainWindow", "Basic"))
        self.portStill.setText(_translate("MainWindow", "Use Still Port"))
        self.portStill.setProperty("port", _translate("MainWindow", "still"))
        self.portVideo.setText(_translate("MainWindow", "Use Video Port"))
        self.portVideo.setProperty("port", _translate("MainWindow", "video"))
        self.checkBox_2.setText(_translate("MainWindow", "Video denoise"))
        self.checkBox_3.setText(_translate("MainWindow", "Video stabilization"))
        self.checkBox.setText(_translate("MainWindow", "Image denoise"))
        self.portSelectionLabel.setText(_translate("MainWindow", "Select port for image captures"))
        self.fixedRes.setText(_translate("MainWindow", "Use fixed"))
        self.fixedRes.setProperty("resolution", _translate("MainWindow", "fixed"))
        self.customRes.setText(_translate("MainWindow", "Custom"))
        self.customRes.setProperty("resolution", _translate("MainWindow", "custom"))
        self.widthComboLabel.setText(_translate("MainWindow", "width:"))
        self.heightComboLabel.setText(_translate("MainWindow", "height"))
        self.actualWidthLabel.setText(_translate("MainWindow", "actual:"))
        self.actualheight.setText(_translate("MainWindow", "width"))
        self.actualHeightLabel.setText(_translate("MainWindow", "actual:"))
        self.actualwidth.setText(_translate("MainWindow", "height"))
        self.zoomSelectionLabel.setText(_translate("MainWindow", "Zoom region of interest before taking picture/video"))
        self.pushButton.setText(_translate("MainWindow", "Apply"))
        self.radioButton_5.setText(_translate("MainWindow", "none (default)"))
        self.radioButton_6.setText(_translate("MainWindow", "resize"))
        self.brightnessLabel.setText(_translate("MainWindow", "Brightness"))
        self.contrastLabel.setText(_translate("MainWindow", "Contrast"))
        self.saturationLabel.setText(_translate("MainWindow", "Saturation"))
        self.sharpnessLabel.setText(_translate("MainWindow", "Sharpness"))
        self.noEffect.setText(_translate("MainWindow", "none"))
        self.selectEffect.setText(_translate("MainWindow", "Select Effect"))
        self.resSelectionLabel.setText(_translate("MainWindow", "Picture/video capture size in pixels"))
        self.resizeSelectionLabel.setText(_translate("MainWindow", "Resize image after taking picture/video"))
        self.adjustmentSelectionLabel.setText(_translate("MainWindow", "Quick adjustments"))
        self.effectSelectionLabel.setText(_translate("MainWindow", "Preprogrammed image effects"))
        self.flashSelectionLabel.setText(_translate("MainWindow", "LED and Flash mode"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.basic), _translate("MainWindow", "Basic"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.exposure), _translate("MainWindow", "Exposure"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.advanced), _translate("MainWindow", "Advanced"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
        self.actionPreferences.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))

